# Generated by Django 3.1.5 on 2021-01-16 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('list_of_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_class_attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('present_or_not_present', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_classes.list_of_classes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.login')),
            ],
        ),
    ]
